#!/bin/bash
VAR1=$(screen -list)
DIR="$HOME/discord_bots/jellycraft"
if [[ $VAR1 != *"jellybot-main"* ]]; then
 echo "Bot Inactive."
 screen -A -m -d -S jellybot-main bash -c "cd $DIR;poetry run python main.py --config config.json"
 echo "Restarted."
fi
