#!/bin/bash
VAR1=$(screen -list)
DIR="/home/bots/jellybot"
if [[ $VAR1 != *"jellybot-main"* ]]; then
 echo "Bot Active."
 screen -X -S jellybot-main quit
else
 echo "Bot Inactive."
fi
screen -A -m -d -S jellybot-main bash -c "cd $DIR;python3.9 bot.py --config config.json"
echo "Restarted."
